# ============================================================================
# STAGING LAYER SCHEMA
# ============================================================================
# Defines tests and documentation for staging models.
# Staging models clean raw source data with light transformations.
#
# Tests applied:
#   - Primary keys: unique + not_null
#   - Foreign keys: relationships
#   - Enums: accepted_values
# ============================================================================

version: 2

models:
  # Customers - master customer data with full_name derived field
  - name: stg_customers
    description: "Staged customer data with standardized fields and full name concatenation"
    columns:
      - name: customer_id
        description: "Primary key for customers"
        tests:
          - unique
          - not_null
      - name: email
        description: "Customer email address - not unique due to source data quality"
        tests:
          - not_null
      - name: first_name
        description: "Customer first name"
        tests:
          - not_null
      - name: last_name
        description: "Customer last name"
        tests:
          - not_null
      - name: full_name
        description: "Concatenated first and last name"
      - name: phone
        description: "Customer phone number"
      - name: address
        description: "Street address"
      - name: city
        description: "City"
      - name: state
        description: "State abbreviation"
      - name: zip_code
        description: "ZIP/Postal code"
      - name: country
        description: "Country"
      - name: segment
        description: "Customer segment classification"
        tests:
          - accepted_values:
              values: ['new', 'occasional', 'regular', 'premium']
      - name: registration_date
        description: "Date customer registered"
        tests:
          - not_null
      - name: is_active
        description: "Whether customer account is active"
        tests:
          - not_null
      - name: created_at
        description: "Record creation timestamp"
      - name: updated_at
        description: "Record last update timestamp"

  # Orders - order headers with date extraction
  - name: stg_orders
    description: "Staged order data with extracted date fields"
    columns:
      - name: order_id
        description: "Primary key for orders"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customers"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_date
        description: "Full timestamp of order"
        tests:
          - not_null
      - name: order_date_day
        description: "Date portion of order timestamp"
      - name: status
        description: "Order status"
        tests:
          - not_null
          - accepted_values:
              values: ['processing', 'shipped', 'completed', 'cancelled', 'returned']
      - name: subtotal
        description: "Order subtotal before shipping and tax"
        tests:
          - not_null
      - name: shipping
        description: "Shipping cost"
      - name: tax
        description: "Tax amount"
      - name: total
        description: "Total order amount"
        tests:
          - not_null
      - name: payment_method
        description: "Payment method used"
        tests:
          - accepted_values:
              values: ['credit_card', 'debit_card', 'paypal', 'apple_pay']
      - name: shipping_address
        description: "Shipping street address"
      - name: shipping_city
        description: "Shipping city"
      - name: shipping_state
        description: "Shipping state"
      - name: shipping_zip
        description: "Shipping ZIP code"
      - name: created_at
        description: "Record creation timestamp"
      - name: updated_at
        description: "Record last update timestamp"

  # Products - product catalog with margin calculations
  - name: stg_products
    description: "Staged product data with calculated margin fields"
    columns:
      - name: product_id
        description: "Primary key for products"
        tests:
          - unique
          - not_null
      - name: sku
        description: "Stock keeping unit"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Product display name"
        tests:
          - not_null
      - name: description
        description: "Product description"
      - name: category_id
        description: "Foreign key to category"
        tests:
          - not_null
      - name: category_name
        description: "Denormalized category name"
        tests:
          - not_null
      - name: price
        description: "Selling price"
        tests:
          - not_null
      - name: cost
        description: "Cost of goods"
        tests:
          - not_null
      - name: profit_margin
        description: "Calculated profit margin (price - cost)"
      - name: margin_percent
        description: "Margin as percentage of price"
      - name: stock_quantity
        description: "Current inventory level"
        tests:
          - not_null
      - name: is_active
        description: "Whether product is active"
        tests:
          - not_null
      - name: created_at
        description: "Record creation timestamp"
      - name: updated_at
        description: "Record last update timestamp"

  # Order Items - line items with discount calculations
  - name: stg_order_items
    description: "Staged order line items with calculated discount fields"
    columns:
      - name: order_item_id
        description: "Primary key for order items"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to orders"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        description: "Foreign key to products"
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: quantity
        description: "Quantity ordered"
        tests:
          - not_null
      - name: unit_price
        description: "Price per unit at time of order"
        tests:
          - not_null
      - name: discount
        description: "Discount amount applied"
      - name: line_total
        description: "Total for line item"
        tests:
          - not_null
      - name: discounted_price
        description: "Unit price after discount"
      - name: discount_percent
        description: "Discount as percentage of unit price"