# ============================================================================
# SOURCE DEFINITIONS
# ============================================================================
# Defines raw source tables and freshness checks.
# Run: dbt source freshness
# ============================================================================

version: 2

sources:
  - name: staging
    database: ecommerce_dw
    schema: staging
    description: "Raw e-commerce data loaded from CSV files"
    
    # Default freshness for all tables
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: updated_at

    tables:
      - name: customers
        description: "Raw customer data"
        columns:
          - name: customer_id
            description: "Primary key"
          - name: email
            description: "Customer email"

      - name: products
        description: "Raw product catalog"
        columns:
          - name: product_id
            description: "Primary key"

      - name: categories
        description: "Product categories"
        freshness: null  # No timestamp column

      - name: orders
        description: "Raw order headers"
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        columns:
          - name: order_id
            description: "Primary key"

      - name: order_items
        description: "Raw order line items"
        freshness: null  # No timestamp column